//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Super.Appaltatore.ReadModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AppaltatoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AppaltatoreEntities object using the connection string found in the 'AppaltatoreEntities' section of the application configuration file.
        /// </summary>
        public AppaltatoreEntities() : base("name=AppaltatoreEntities", "AppaltatoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppaltatoreEntities object.
        /// </summary>
        public AppaltatoreEntities(string connectionString) : base(connectionString, "AppaltatoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppaltatoreEntities object.
        /// </summary>
        public AppaltatoreEntities(EntityConnection connection) : base(connection, "AppaltatoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConsuntivazioneRot> ConsuntivazioneRots
        {
            get
            {
                if ((_ConsuntivazioneRots == null))
                {
                    _ConsuntivazioneRots = base.CreateObjectSet<ConsuntivazioneRot>("ConsuntivazioneRots");
                }
                return _ConsuntivazioneRots;
            }
        }
        private ObjectSet<ConsuntivazioneRot> _ConsuntivazioneRots;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LastEventsReadAppaltatore> LastEventsReadAppaltatores
        {
            get
            {
                if ((_LastEventsReadAppaltatores == null))
                {
                    _LastEventsReadAppaltatores = base.CreateObjectSet<LastEventsReadAppaltatore>("LastEventsReadAppaltatores");
                }
                return _LastEventsReadAppaltatores;
            }
        }
        private ObjectSet<LastEventsReadAppaltatore> _LastEventsReadAppaltatores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Appaltatore> Appaltatores
        {
            get
            {
                if ((_Appaltatores == null))
                {
                    _Appaltatores = base.CreateObjectSet<Appaltatore>("Appaltatores");
                }
                return _Appaltatores;
            }
        }
        private ObjectSet<Appaltatore> _Appaltatores;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConsuntivazioneRots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsuntivazioneRots(ConsuntivazioneRot consuntivazioneRot)
        {
            base.AddObject("ConsuntivazioneRots", consuntivazioneRot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LastEventsReadAppaltatores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLastEventsReadAppaltatores(LastEventsReadAppaltatore lastEventsReadAppaltatore)
        {
            base.AddObject("LastEventsReadAppaltatores", lastEventsReadAppaltatore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Appaltatores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppaltatores(Appaltatore appaltatore)
        {
            base.AddObject("Appaltatores", appaltatore);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Super.Appaltatore.ReadModel", Name="Appaltatore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Appaltatore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Appaltatore object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        public static Appaltatore CreateAppaltatore(global::System.Guid id, global::System.Int64 version, global::System.DateTime creationDate, global::System.Boolean deleted)
        {
            Appaltatore appaltatore = new Appaltatore();
            appaltatore.Id = id;
            appaltatore.Version = version;
            appaltatore.CreationDate = creationDate;
            appaltatore.Deleted = deleted;
            return appaltatore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Int64 _Version;
        partial void OnVersionChanging(global::System.Int64 value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Super.Appaltatore.ReadModel", Name="ConsuntivazioneRot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConsuntivazioneRot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConsuntivazioneRot object.
        /// </summary>
        /// <param name="idIntervento">Initial value of the IdIntervento property.</param>
        /// <param name="idCommittente">Initial value of the IdCommittente property.</param>
        /// <param name="idLotto">Initial value of the IdLotto property.</param>
        /// <param name="idImpianto">Initial value of the IdImpianto property.</param>
        /// <param name="idTipoIntervento">Initial value of the IdTipoIntervento property.</param>
        /// <param name="isAvvisoIspezione">Initial value of the IsAvvisoIspezione property.</param>
        /// <param name="isSpunta">Initial value of the IsSpunta property.</param>
        /// <param name="isReso">Initial value of the IsReso property.</param>
        /// <param name="isNonResoAppaltatore">Initial value of the IsNonResoAppaltatore property.</param>
        /// <param name="isNonReso20mn">Initial value of the IsNonReso20mn property.</param>
        /// <param name="isNonResoTrenitalia">Initial value of the IsNonResoTrenitalia property.</param>
        /// <param name="isRilevatoNonReso">Initial value of the IsRilevatoNonReso property.</param>
        /// <param name="isRettifica">Initial value of the IsRettifica property.</param>
        /// <param name="isSostituito">Initial value of the IsSostituito property.</param>
        /// <param name="hasSchedaV">Initial value of the HasSchedaV property.</param>
        /// <param name="hasSchedaQ">Initial value of the HasSchedaQ property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        /// <param name="startDateProgrammata">Initial value of the StartDateProgrammata property.</param>
        /// <param name="endDateProgrammata">Initial value of the EndDateProgrammata property.</param>
        /// <param name="startDateConsuntivataAppaltatore">Initial value of the StartDateConsuntivataAppaltatore property.</param>
        /// <param name="endDateConsuntivataAppaltatore">Initial value of the EndDateConsuntivataAppaltatore property.</param>
        /// <param name="isProgrammato">Initial value of the IsProgrammato property.</param>
        /// <param name="isPLX">Initial value of the IsPLX property.</param>
        /// <param name="isEstemporaneo">Initial value of the IsEstemporaneo property.</param>
        /// <param name="isSostitutivo">Initial value of the IsSostitutivo property.</param>
        /// <param name="hasTreni">Initial value of the HasTreni property.</param>
        /// <param name="hasRotabiliSingoli">Initial value of the HasRotabiliSingoli property.</param>
        /// <param name="hasCarozze">Initial value of the HasCarozze property.</param>
        /// <param name="hasLocomotive">Initial value of the HasLocomotive property.</param>
        /// <param name="isModificatoTrenitaliaRispettoAlProgramma">Initial value of the IsModificatoTrenitaliaRispettoAlProgramma property.</param>
        /// <param name="isModificatoAppaltatoreRispettoAlProgramma">Initial value of the IsModificatoAppaltatoreRispettoAlProgramma property.</param>
        /// <param name="isModificatoTrenitaliaRispettoAllAppaltatore">Initial value of the IsModificatoTrenitaliaRispettoAllAppaltatore property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        public static ConsuntivazioneRot CreateConsuntivazioneRot(global::System.Guid idIntervento, global::System.Guid idCommittente, global::System.Guid idLotto, global::System.Guid idImpianto, global::System.Guid idTipoIntervento, global::System.Boolean isAvvisoIspezione, global::System.Boolean isSpunta, global::System.Boolean isReso, global::System.Boolean isNonResoAppaltatore, global::System.Boolean isNonReso20mn, global::System.Boolean isNonResoTrenitalia, global::System.Boolean isRilevatoNonReso, global::System.Boolean isRettifica, global::System.Boolean isSostituito, global::System.Boolean hasSchedaV, global::System.Boolean hasSchedaQ, global::System.DateTime start, global::System.DateTime end, global::System.DateTime startDateProgrammata, global::System.DateTime endDateProgrammata, global::System.DateTime startDateConsuntivataAppaltatore, global::System.DateTime endDateConsuntivataAppaltatore, global::System.Boolean isProgrammato, global::System.Boolean isPLX, global::System.Boolean isEstemporaneo, global::System.Boolean isSostitutivo, global::System.Boolean hasTreni, global::System.Boolean hasRotabiliSingoli, global::System.Boolean hasCarozze, global::System.Boolean hasLocomotive, global::System.Boolean isModificatoTrenitaliaRispettoAlProgramma, global::System.Boolean isModificatoAppaltatoreRispettoAlProgramma, global::System.Boolean isModificatoTrenitaliaRispettoAllAppaltatore, global::System.DateTime creationDate, global::System.Boolean deleted)
        {
            ConsuntivazioneRot consuntivazioneRot = new ConsuntivazioneRot();
            consuntivazioneRot.IdIntervento = idIntervento;
            consuntivazioneRot.IdCommittente = idCommittente;
            consuntivazioneRot.IdLotto = idLotto;
            consuntivazioneRot.IdImpianto = idImpianto;
            consuntivazioneRot.IdTipoIntervento = idTipoIntervento;
            consuntivazioneRot.IsAvvisoIspezione = isAvvisoIspezione;
            consuntivazioneRot.IsSpunta = isSpunta;
            consuntivazioneRot.IsReso = isReso;
            consuntivazioneRot.IsNonResoAppaltatore = isNonResoAppaltatore;
            consuntivazioneRot.IsNonReso20mn = isNonReso20mn;
            consuntivazioneRot.IsNonResoTrenitalia = isNonResoTrenitalia;
            consuntivazioneRot.IsRilevatoNonReso = isRilevatoNonReso;
            consuntivazioneRot.IsRettifica = isRettifica;
            consuntivazioneRot.IsSostituito = isSostituito;
            consuntivazioneRot.HasSchedaV = hasSchedaV;
            consuntivazioneRot.HasSchedaQ = hasSchedaQ;
            consuntivazioneRot.Start = start;
            consuntivazioneRot.End = end;
            consuntivazioneRot.StartDateProgrammata = startDateProgrammata;
            consuntivazioneRot.EndDateProgrammata = endDateProgrammata;
            consuntivazioneRot.StartDateConsuntivataAppaltatore = startDateConsuntivataAppaltatore;
            consuntivazioneRot.EndDateConsuntivataAppaltatore = endDateConsuntivataAppaltatore;
            consuntivazioneRot.IsProgrammato = isProgrammato;
            consuntivazioneRot.IsPLX = isPLX;
            consuntivazioneRot.IsEstemporaneo = isEstemporaneo;
            consuntivazioneRot.IsSostitutivo = isSostitutivo;
            consuntivazioneRot.HasTreni = hasTreni;
            consuntivazioneRot.HasRotabiliSingoli = hasRotabiliSingoli;
            consuntivazioneRot.HasCarozze = hasCarozze;
            consuntivazioneRot.HasLocomotive = hasLocomotive;
            consuntivazioneRot.IsModificatoTrenitaliaRispettoAlProgramma = isModificatoTrenitaliaRispettoAlProgramma;
            consuntivazioneRot.IsModificatoAppaltatoreRispettoAlProgramma = isModificatoAppaltatoreRispettoAlProgramma;
            consuntivazioneRot.IsModificatoTrenitaliaRispettoAllAppaltatore = isModificatoTrenitaliaRispettoAllAppaltatore;
            consuntivazioneRot.CreationDate = creationDate;
            consuntivazioneRot.Deleted = deleted;
            return consuntivazioneRot;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdIntervento
        {
            get
            {
                return _IdIntervento;
            }
            set
            {
                if (_IdIntervento != value)
                {
                    OnIdInterventoChanging(value);
                    ReportPropertyChanging("IdIntervento");
                    _IdIntervento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdIntervento");
                    OnIdInterventoChanged();
                }
            }
        }
        private global::System.Guid _IdIntervento;
        partial void OnIdInterventoChanging(global::System.Guid value);
        partial void OnIdInterventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdCommittente
        {
            get
            {
                return _IdCommittente;
            }
            set
            {
                OnIdCommittenteChanging(value);
                ReportPropertyChanging("IdCommittente");
                _IdCommittente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCommittente");
                OnIdCommittenteChanged();
            }
        }
        private global::System.Guid _IdCommittente;
        partial void OnIdCommittenteChanging(global::System.Guid value);
        partial void OnIdCommittenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdLotto
        {
            get
            {
                return _IdLotto;
            }
            set
            {
                OnIdLottoChanging(value);
                ReportPropertyChanging("IdLotto");
                _IdLotto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdLotto");
                OnIdLottoChanged();
            }
        }
        private global::System.Guid _IdLotto;
        partial void OnIdLottoChanging(global::System.Guid value);
        partial void OnIdLottoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdImpianto
        {
            get
            {
                return _IdImpianto;
            }
            set
            {
                OnIdImpiantoChanging(value);
                ReportPropertyChanging("IdImpianto");
                _IdImpianto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdImpianto");
                OnIdImpiantoChanged();
            }
        }
        private global::System.Guid _IdImpianto;
        partial void OnIdImpiantoChanging(global::System.Guid value);
        partial void OnIdImpiantoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdTipoIntervento
        {
            get
            {
                return _IdTipoIntervento;
            }
            set
            {
                OnIdTipoInterventoChanging(value);
                ReportPropertyChanging("IdTipoIntervento");
                _IdTipoIntervento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoIntervento");
                OnIdTipoInterventoChanged();
            }
        }
        private global::System.Guid _IdTipoIntervento;
        partial void OnIdTipoInterventoChanging(global::System.Guid value);
        partial void OnIdTipoInterventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodiceOrdine
        {
            get
            {
                return _CodiceOrdine;
            }
            set
            {
                OnCodiceOrdineChanging(value);
                ReportPropertyChanging("CodiceOrdine");
                _CodiceOrdine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodiceOrdine");
                OnCodiceOrdineChanged();
            }
        }
        private global::System.String _CodiceOrdine;
        partial void OnCodiceOrdineChanging(global::System.String value);
        partial void OnCodiceOrdineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAvvisoIspezione
        {
            get
            {
                return _IsAvvisoIspezione;
            }
            set
            {
                OnIsAvvisoIspezioneChanging(value);
                ReportPropertyChanging("IsAvvisoIspezione");
                _IsAvvisoIspezione = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAvvisoIspezione");
                OnIsAvvisoIspezioneChanged();
            }
        }
        private global::System.Boolean _IsAvvisoIspezione;
        partial void OnIsAvvisoIspezioneChanging(global::System.Boolean value);
        partial void OnIsAvvisoIspezioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSpunta
        {
            get
            {
                return _IsSpunta;
            }
            set
            {
                OnIsSpuntaChanging(value);
                ReportPropertyChanging("IsSpunta");
                _IsSpunta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSpunta");
                OnIsSpuntaChanged();
            }
        }
        private global::System.Boolean _IsSpunta;
        partial void OnIsSpuntaChanging(global::System.Boolean value);
        partial void OnIsSpuntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReso
        {
            get
            {
                return _IsReso;
            }
            set
            {
                OnIsResoChanging(value);
                ReportPropertyChanging("IsReso");
                _IsReso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReso");
                OnIsResoChanged();
            }
        }
        private global::System.Boolean _IsReso;
        partial void OnIsResoChanging(global::System.Boolean value);
        partial void OnIsResoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonResoAppaltatore
        {
            get
            {
                return _IsNonResoAppaltatore;
            }
            set
            {
                OnIsNonResoAppaltatoreChanging(value);
                ReportPropertyChanging("IsNonResoAppaltatore");
                _IsNonResoAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonResoAppaltatore");
                OnIsNonResoAppaltatoreChanged();
            }
        }
        private global::System.Boolean _IsNonResoAppaltatore;
        partial void OnIsNonResoAppaltatoreChanging(global::System.Boolean value);
        partial void OnIsNonResoAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonReso20mn
        {
            get
            {
                return _IsNonReso20mn;
            }
            set
            {
                OnIsNonReso20mnChanging(value);
                ReportPropertyChanging("IsNonReso20mn");
                _IsNonReso20mn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonReso20mn");
                OnIsNonReso20mnChanged();
            }
        }
        private global::System.Boolean _IsNonReso20mn;
        partial void OnIsNonReso20mnChanging(global::System.Boolean value);
        partial void OnIsNonReso20mnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonResoTrenitalia
        {
            get
            {
                return _IsNonResoTrenitalia;
            }
            set
            {
                OnIsNonResoTrenitaliaChanging(value);
                ReportPropertyChanging("IsNonResoTrenitalia");
                _IsNonResoTrenitalia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonResoTrenitalia");
                OnIsNonResoTrenitaliaChanged();
            }
        }
        private global::System.Boolean _IsNonResoTrenitalia;
        partial void OnIsNonResoTrenitaliaChanging(global::System.Boolean value);
        partial void OnIsNonResoTrenitaliaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRilevatoNonReso
        {
            get
            {
                return _IsRilevatoNonReso;
            }
            set
            {
                OnIsRilevatoNonResoChanging(value);
                ReportPropertyChanging("IsRilevatoNonReso");
                _IsRilevatoNonReso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRilevatoNonReso");
                OnIsRilevatoNonResoChanged();
            }
        }
        private global::System.Boolean _IsRilevatoNonReso;
        partial void OnIsRilevatoNonResoChanging(global::System.Boolean value);
        partial void OnIsRilevatoNonResoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRettifica
        {
            get
            {
                return _IsRettifica;
            }
            set
            {
                OnIsRettificaChanging(value);
                ReportPropertyChanging("IsRettifica");
                _IsRettifica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRettifica");
                OnIsRettificaChanged();
            }
        }
        private global::System.Boolean _IsRettifica;
        partial void OnIsRettificaChanging(global::System.Boolean value);
        partial void OnIsRettificaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSostituito
        {
            get
            {
                return _IsSostituito;
            }
            set
            {
                OnIsSostituitoChanging(value);
                ReportPropertyChanging("IsSostituito");
                _IsSostituito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSostituito");
                OnIsSostituitoChanged();
            }
        }
        private global::System.Boolean _IsSostituito;
        partial void OnIsSostituitoChanging(global::System.Boolean value);
        partial void OnIsSostituitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasSchedaV
        {
            get
            {
                return _HasSchedaV;
            }
            set
            {
                OnHasSchedaVChanging(value);
                ReportPropertyChanging("HasSchedaV");
                _HasSchedaV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasSchedaV");
                OnHasSchedaVChanged();
            }
        }
        private global::System.Boolean _HasSchedaV;
        partial void OnHasSchedaVChanging(global::System.Boolean value);
        partial void OnHasSchedaVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasSchedaQ
        {
            get
            {
                return _HasSchedaQ;
            }
            set
            {
                OnHasSchedaQChanging(value);
                ReportPropertyChanging("HasSchedaQ");
                _HasSchedaQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasSchedaQ");
                OnHasSchedaQChanged();
            }
        }
        private global::System.Boolean _HasSchedaQ;
        partial void OnHasSchedaQChanging(global::System.Boolean value);
        partial void OnHasSchedaQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroTrenoPartenza
        {
            get
            {
                return _NumeroTrenoPartenza;
            }
            set
            {
                OnNumeroTrenoPartenzaChanging(value);
                ReportPropertyChanging("NumeroTrenoPartenza");
                _NumeroTrenoPartenza = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroTrenoPartenza");
                OnNumeroTrenoPartenzaChanged();
            }
        }
        private global::System.String _NumeroTrenoPartenza;
        partial void OnNumeroTrenoPartenzaChanging(global::System.String value);
        partial void OnNumeroTrenoPartenzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataTrenoPartenza
        {
            get
            {
                return _DataTrenoPartenza;
            }
            set
            {
                OnDataTrenoPartenzaChanging(value);
                ReportPropertyChanging("DataTrenoPartenza");
                _DataTrenoPartenza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataTrenoPartenza");
                OnDataTrenoPartenzaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataTrenoPartenza;
        partial void OnDataTrenoPartenzaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataTrenoPartenzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDateProgrammata
        {
            get
            {
                return _StartDateProgrammata;
            }
            set
            {
                OnStartDateProgrammataChanging(value);
                ReportPropertyChanging("StartDateProgrammata");
                _StartDateProgrammata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDateProgrammata");
                OnStartDateProgrammataChanged();
            }
        }
        private global::System.DateTime _StartDateProgrammata;
        partial void OnStartDateProgrammataChanging(global::System.DateTime value);
        partial void OnStartDateProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDateProgrammata
        {
            get
            {
                return _EndDateProgrammata;
            }
            set
            {
                OnEndDateProgrammataChanging(value);
                ReportPropertyChanging("EndDateProgrammata");
                _EndDateProgrammata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateProgrammata");
                OnEndDateProgrammataChanged();
            }
        }
        private global::System.DateTime _EndDateProgrammata;
        partial void OnEndDateProgrammataChanging(global::System.DateTime value);
        partial void OnEndDateProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComposizioneProgrammata
        {
            get
            {
                return _ComposizioneProgrammata;
            }
            set
            {
                OnComposizioneProgrammataChanging(value);
                ReportPropertyChanging("ComposizioneProgrammata");
                _ComposizioneProgrammata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ComposizioneProgrammata");
                OnComposizioneProgrammataChanged();
            }
        }
        private global::System.String _ComposizioneProgrammata;
        partial void OnComposizioneProgrammataChanging(global::System.String value);
        partial void OnComposizioneProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDateConsuntivataAppaltatore
        {
            get
            {
                return _StartDateConsuntivataAppaltatore;
            }
            set
            {
                OnStartDateConsuntivataAppaltatoreChanging(value);
                ReportPropertyChanging("StartDateConsuntivataAppaltatore");
                _StartDateConsuntivataAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDateConsuntivataAppaltatore");
                OnStartDateConsuntivataAppaltatoreChanged();
            }
        }
        private global::System.DateTime _StartDateConsuntivataAppaltatore;
        partial void OnStartDateConsuntivataAppaltatoreChanging(global::System.DateTime value);
        partial void OnStartDateConsuntivataAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDateConsuntivataAppaltatore
        {
            get
            {
                return _EndDateConsuntivataAppaltatore;
            }
            set
            {
                OnEndDateConsuntivataAppaltatoreChanging(value);
                ReportPropertyChanging("EndDateConsuntivataAppaltatore");
                _EndDateConsuntivataAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateConsuntivataAppaltatore");
                OnEndDateConsuntivataAppaltatoreChanged();
            }
        }
        private global::System.DateTime _EndDateConsuntivataAppaltatore;
        partial void OnEndDateConsuntivataAppaltatoreChanging(global::System.DateTime value);
        partial void OnEndDateConsuntivataAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsProgrammato
        {
            get
            {
                return _IsProgrammato;
            }
            set
            {
                OnIsProgrammatoChanging(value);
                ReportPropertyChanging("IsProgrammato");
                _IsProgrammato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProgrammato");
                OnIsProgrammatoChanged();
            }
        }
        private global::System.Boolean _IsProgrammato;
        partial void OnIsProgrammatoChanging(global::System.Boolean value);
        partial void OnIsProgrammatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPLX
        {
            get
            {
                return _IsPLX;
            }
            set
            {
                OnIsPLXChanging(value);
                ReportPropertyChanging("IsPLX");
                _IsPLX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPLX");
                OnIsPLXChanged();
            }
        }
        private global::System.Boolean _IsPLX;
        partial void OnIsPLXChanging(global::System.Boolean value);
        partial void OnIsPLXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEstemporaneo
        {
            get
            {
                return _IsEstemporaneo;
            }
            set
            {
                OnIsEstemporaneoChanging(value);
                ReportPropertyChanging("IsEstemporaneo");
                _IsEstemporaneo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEstemporaneo");
                OnIsEstemporaneoChanged();
            }
        }
        private global::System.Boolean _IsEstemporaneo;
        partial void OnIsEstemporaneoChanging(global::System.Boolean value);
        partial void OnIsEstemporaneoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSostitutivo
        {
            get
            {
                return _IsSostitutivo;
            }
            set
            {
                OnIsSostitutivoChanging(value);
                ReportPropertyChanging("IsSostitutivo");
                _IsSostitutivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSostitutivo");
                OnIsSostitutivoChanged();
            }
        }
        private global::System.Boolean _IsSostitutivo;
        partial void OnIsSostitutivoChanging(global::System.Boolean value);
        partial void OnIsSostitutivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasTreni
        {
            get
            {
                return _HasTreni;
            }
            set
            {
                OnHasTreniChanging(value);
                ReportPropertyChanging("HasTreni");
                _HasTreni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasTreni");
                OnHasTreniChanged();
            }
        }
        private global::System.Boolean _HasTreni;
        partial void OnHasTreniChanging(global::System.Boolean value);
        partial void OnHasTreniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasRotabiliSingoli
        {
            get
            {
                return _HasRotabiliSingoli;
            }
            set
            {
                OnHasRotabiliSingoliChanging(value);
                ReportPropertyChanging("HasRotabiliSingoli");
                _HasRotabiliSingoli = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasRotabiliSingoli");
                OnHasRotabiliSingoliChanged();
            }
        }
        private global::System.Boolean _HasRotabiliSingoli;
        partial void OnHasRotabiliSingoliChanging(global::System.Boolean value);
        partial void OnHasRotabiliSingoliChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasCarozze
        {
            get
            {
                return _HasCarozze;
            }
            set
            {
                OnHasCarozzeChanging(value);
                ReportPropertyChanging("HasCarozze");
                _HasCarozze = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasCarozze");
                OnHasCarozzeChanged();
            }
        }
        private global::System.Boolean _HasCarozze;
        partial void OnHasCarozzeChanging(global::System.Boolean value);
        partial void OnHasCarozzeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasLocomotive
        {
            get
            {
                return _HasLocomotive;
            }
            set
            {
                OnHasLocomotiveChanging(value);
                ReportPropertyChanging("HasLocomotive");
                _HasLocomotive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasLocomotive");
                OnHasLocomotiveChanged();
            }
        }
        private global::System.Boolean _HasLocomotive;
        partial void OnHasLocomotiveChanging(global::System.Boolean value);
        partial void OnHasLocomotiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoTrenitaliaRispettoAlProgramma
        {
            get
            {
                return _IsModificatoTrenitaliaRispettoAlProgramma;
            }
            set
            {
                OnIsModificatoTrenitaliaRispettoAlProgrammaChanging(value);
                ReportPropertyChanging("IsModificatoTrenitaliaRispettoAlProgramma");
                _IsModificatoTrenitaliaRispettoAlProgramma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoTrenitaliaRispettoAlProgramma");
                OnIsModificatoTrenitaliaRispettoAlProgrammaChanged();
            }
        }
        private global::System.Boolean _IsModificatoTrenitaliaRispettoAlProgramma;
        partial void OnIsModificatoTrenitaliaRispettoAlProgrammaChanging(global::System.Boolean value);
        partial void OnIsModificatoTrenitaliaRispettoAlProgrammaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoAppaltatoreRispettoAlProgramma
        {
            get
            {
                return _IsModificatoAppaltatoreRispettoAlProgramma;
            }
            set
            {
                OnIsModificatoAppaltatoreRispettoAlProgrammaChanging(value);
                ReportPropertyChanging("IsModificatoAppaltatoreRispettoAlProgramma");
                _IsModificatoAppaltatoreRispettoAlProgramma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoAppaltatoreRispettoAlProgramma");
                OnIsModificatoAppaltatoreRispettoAlProgrammaChanged();
            }
        }
        private global::System.Boolean _IsModificatoAppaltatoreRispettoAlProgramma;
        partial void OnIsModificatoAppaltatoreRispettoAlProgrammaChanging(global::System.Boolean value);
        partial void OnIsModificatoAppaltatoreRispettoAlProgrammaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoTrenitaliaRispettoAllAppaltatore
        {
            get
            {
                return _IsModificatoTrenitaliaRispettoAllAppaltatore;
            }
            set
            {
                OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanging(value);
                ReportPropertyChanging("IsModificatoTrenitaliaRispettoAllAppaltatore");
                _IsModificatoTrenitaliaRispettoAllAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoTrenitaliaRispettoAllAppaltatore");
                OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanged();
            }
        }
        private global::System.Boolean _IsModificatoTrenitaliaRispettoAllAppaltatore;
        partial void OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanging(global::System.Boolean value);
        partial void OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Super.Appaltatore.ReadModel", Name="LastEventsReadAppaltatore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LastEventsReadAppaltatore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LastEventsReadAppaltatore object.
        /// </summary>
        /// <param name="commitId">Initial value of the CommitId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static LastEventsReadAppaltatore CreateLastEventsReadAppaltatore(global::System.Guid commitId, global::System.DateTime date)
        {
            LastEventsReadAppaltatore lastEventsReadAppaltatore = new LastEventsReadAppaltatore();
            lastEventsReadAppaltatore.CommitId = commitId;
            lastEventsReadAppaltatore.Date = date;
            return lastEventsReadAppaltatore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CommitId
        {
            get
            {
                return _CommitId;
            }
            set
            {
                if (_CommitId != value)
                {
                    OnCommitIdChanging(value);
                    ReportPropertyChanging("CommitId");
                    _CommitId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommitId");
                    OnCommitIdChanged();
                }
            }
        }
        private global::System.Guid _CommitId;
        partial void OnCommitIdChanging(global::System.Guid value);
        partial void OnCommitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion

    
    }

    #endregion

    
}
