//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Super.Administration.ReadModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AppaltatoreContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AppaltatoreContainer object using the connection string found in the 'AppaltatoreContainer' section of the application configuration file.
        /// </summary>
        public AppaltatoreContainer() : base("name=AppaltatoreContainer", "AppaltatoreContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppaltatoreContainer object.
        /// </summary>
        public AppaltatoreContainer(string connectionString) : base(connectionString, "AppaltatoreContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppaltatoreContainer object.
        /// </summary>
        public AppaltatoreContainer(EntityConnection connection) : base(connection, "AppaltatoreContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConsuntivazioneRot> ConsuntivazioneRots
        {
            get
            {
                if ((_ConsuntivazioneRots == null))
                {
                    _ConsuntivazioneRots = base.CreateObjectSet<ConsuntivazioneRot>("ConsuntivazioneRots");
                }
                return _ConsuntivazioneRots;
            }
        }
        private ObjectSet<ConsuntivazioneRot> _ConsuntivazioneRots;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConsuntivazioneRots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsuntivazioneRots(ConsuntivazioneRot consuntivazioneRot)
        {
            base.AddObject("ConsuntivazioneRots", consuntivazioneRot);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppaltatoreModel", Name="ConsuntivazioneRot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConsuntivazioneRot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConsuntivazioneRot object.
        /// </summary>
        /// <param name="idIntervento">Initial value of the IdIntervento property.</param>
        /// <param name="idCommittente">Initial value of the IdCommittente property.</param>
        /// <param name="idLotto">Initial value of the IdLotto property.</param>
        /// <param name="idAreaIntervento">Initial value of the IdAreaIntervento property.</param>
        /// <param name="idTipoIntervento">Initial value of the IdTipoIntervento property.</param>
        /// <param name="isAvvisoIspezione">Initial value of the IsAvvisoIspezione property.</param>
        /// <param name="isSpunta">Initial value of the IsSpunta property.</param>
        /// <param name="isReso">Initial value of the IsReso property.</param>
        /// <param name="isNonResoAppaltatore">Initial value of the IsNonResoAppaltatore property.</param>
        /// <param name="isNonReso20mn">Initial value of the IsNonReso20mn property.</param>
        /// <param name="isNonResoTrenitalia">Initial value of the IsNonResoTrenitalia property.</param>
        /// <param name="isRilevatoNonReso">Initial value of the IsRilevatoNonReso property.</param>
        /// <param name="isRettifica">Initial value of the IsRettifica property.</param>
        /// <param name="isSostituito">Initial value of the IsSostituito property.</param>
        /// <param name="hasSchedaV">Initial value of the HasSchedaV property.</param>
        /// <param name="hasSchedaQ">Initial value of the HasSchedaQ property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        /// <param name="areaInterventoDescrizione">Initial value of the AreaInterventoDescrizione property.</param>
        /// <param name="tipoInterventoDescrizione">Initial value of the TipoInterventoDescrizione property.</param>
        /// <param name="dataInizioProgrammata">Initial value of the DataInizioProgrammata property.</param>
        /// <param name="dataFineProgrammata">Initial value of the DataFineProgrammata property.</param>
        /// <param name="dataInizioConsuntivataAppaltatore">Initial value of the DataInizioConsuntivataAppaltatore property.</param>
        /// <param name="dataFineConsuntivataAppaltatore">Initial value of the DataFineConsuntivataAppaltatore property.</param>
        /// <param name="isProgrammato">Initial value of the IsProgrammato property.</param>
        /// <param name="isPLX">Initial value of the IsPLX property.</param>
        /// <param name="isEstemporaneo">Initial value of the IsEstemporaneo property.</param>
        /// <param name="isSostitutivo">Initial value of the IsSostitutivo property.</param>
        /// <param name="hasTreni">Initial value of the HasTreni property.</param>
        /// <param name="hasRotabiliSingoli">Initial value of the HasRotabiliSingoli property.</param>
        /// <param name="hasCarozze">Initial value of the HasCarozze property.</param>
        /// <param name="hasLocomotive">Initial value of the HasLocomotive property.</param>
        /// <param name="isModificatoTrenitaliaRispettoAlProgramma">Initial value of the IsModificatoTrenitaliaRispettoAlProgramma property.</param>
        /// <param name="isModificatoAppaltatoreRispettoAlProgramma">Initial value of the IsModificatoAppaltatoreRispettoAlProgramma property.</param>
        /// <param name="isModificatoTrenitaliaRispettoAllAppaltatore">Initial value of the IsModificatoTrenitaliaRispettoAllAppaltatore property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        public static ConsuntivazioneRot CreateConsuntivazioneRot(global::System.Guid idIntervento, global::System.Guid idCommittente, global::System.Guid idLotto, global::System.Guid idAreaIntervento, global::System.Guid idTipoIntervento, global::System.Boolean isAvvisoIspezione, global::System.Boolean isSpunta, global::System.Boolean isReso, global::System.Boolean isNonResoAppaltatore, global::System.Boolean isNonReso20mn, global::System.Boolean isNonResoTrenitalia, global::System.Boolean isRilevatoNonReso, global::System.Boolean isRettifica, global::System.Boolean isSostituito, global::System.Boolean hasSchedaV, global::System.Boolean hasSchedaQ, global::System.DateTime start, global::System.DateTime end, global::System.String areaInterventoDescrizione, global::System.String tipoInterventoDescrizione, global::System.DateTime dataInizioProgrammata, global::System.DateTime dataFineProgrammata, global::System.DateTime dataInizioConsuntivataAppaltatore, global::System.DateTime dataFineConsuntivataAppaltatore, global::System.Boolean isProgrammato, global::System.Boolean isPLX, global::System.Boolean isEstemporaneo, global::System.Boolean isSostitutivo, global::System.Boolean hasTreni, global::System.Boolean hasRotabiliSingoli, global::System.Boolean hasCarozze, global::System.Boolean hasLocomotive, global::System.Boolean isModificatoTrenitaliaRispettoAlProgramma, global::System.Boolean isModificatoAppaltatoreRispettoAlProgramma, global::System.Boolean isModificatoTrenitaliaRispettoAllAppaltatore, global::System.DateTime creationDate, global::System.Boolean deleted)
        {
            ConsuntivazioneRot consuntivazioneRot = new ConsuntivazioneRot();
            consuntivazioneRot.IdIntervento = idIntervento;
            consuntivazioneRot.IdCommittente = idCommittente;
            consuntivazioneRot.IdLotto = idLotto;
            consuntivazioneRot.IdAreaIntervento = idAreaIntervento;
            consuntivazioneRot.IdTipoIntervento = idTipoIntervento;
            consuntivazioneRot.IsAvvisoIspezione = isAvvisoIspezione;
            consuntivazioneRot.IsSpunta = isSpunta;
            consuntivazioneRot.IsReso = isReso;
            consuntivazioneRot.IsNonResoAppaltatore = isNonResoAppaltatore;
            consuntivazioneRot.IsNonReso20mn = isNonReso20mn;
            consuntivazioneRot.IsNonResoTrenitalia = isNonResoTrenitalia;
            consuntivazioneRot.IsRilevatoNonReso = isRilevatoNonReso;
            consuntivazioneRot.IsRettifica = isRettifica;
            consuntivazioneRot.IsSostituito = isSostituito;
            consuntivazioneRot.HasSchedaV = hasSchedaV;
            consuntivazioneRot.HasSchedaQ = hasSchedaQ;
            consuntivazioneRot.Start = start;
            consuntivazioneRot.End = end;
            consuntivazioneRot.AreaInterventoDescrizione = areaInterventoDescrizione;
            consuntivazioneRot.TipoInterventoDescrizione = tipoInterventoDescrizione;
            consuntivazioneRot.DataInizioProgrammata = dataInizioProgrammata;
            consuntivazioneRot.DataFineProgrammata = dataFineProgrammata;
            consuntivazioneRot.DataInizioConsuntivataAppaltatore = dataInizioConsuntivataAppaltatore;
            consuntivazioneRot.DataFineConsuntivataAppaltatore = dataFineConsuntivataAppaltatore;
            consuntivazioneRot.IsProgrammato = isProgrammato;
            consuntivazioneRot.IsPLX = isPLX;
            consuntivazioneRot.IsEstemporaneo = isEstemporaneo;
            consuntivazioneRot.IsSostitutivo = isSostitutivo;
            consuntivazioneRot.HasTreni = hasTreni;
            consuntivazioneRot.HasRotabiliSingoli = hasRotabiliSingoli;
            consuntivazioneRot.HasCarozze = hasCarozze;
            consuntivazioneRot.HasLocomotive = hasLocomotive;
            consuntivazioneRot.IsModificatoTrenitaliaRispettoAlProgramma = isModificatoTrenitaliaRispettoAlProgramma;
            consuntivazioneRot.IsModificatoAppaltatoreRispettoAlProgramma = isModificatoAppaltatoreRispettoAlProgramma;
            consuntivazioneRot.IsModificatoTrenitaliaRispettoAllAppaltatore = isModificatoTrenitaliaRispettoAllAppaltatore;
            consuntivazioneRot.CreationDate = creationDate;
            consuntivazioneRot.Deleted = deleted;
            return consuntivazioneRot;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdIntervento
        {
            get
            {
                return _IdIntervento;
            }
            set
            {
                if (_IdIntervento != value)
                {
                    OnIdInterventoChanging(value);
                    ReportPropertyChanging("IdIntervento");
                    _IdIntervento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdIntervento");
                    OnIdInterventoChanged();
                }
            }
        }
        private global::System.Guid _IdIntervento;
        partial void OnIdInterventoChanging(global::System.Guid value);
        partial void OnIdInterventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdCommittente
        {
            get
            {
                return _IdCommittente;
            }
            set
            {
                OnIdCommittenteChanging(value);
                ReportPropertyChanging("IdCommittente");
                _IdCommittente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCommittente");
                OnIdCommittenteChanged();
            }
        }
        private global::System.Guid _IdCommittente;
        partial void OnIdCommittenteChanging(global::System.Guid value);
        partial void OnIdCommittenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdLotto
        {
            get
            {
                return _IdLotto;
            }
            set
            {
                OnIdLottoChanging(value);
                ReportPropertyChanging("IdLotto");
                _IdLotto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdLotto");
                OnIdLottoChanged();
            }
        }
        private global::System.Guid _IdLotto;
        partial void OnIdLottoChanging(global::System.Guid value);
        partial void OnIdLottoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdAreaIntervento
        {
            get
            {
                return _IdAreaIntervento;
            }
            set
            {
                OnIdAreaInterventoChanging(value);
                ReportPropertyChanging("IdAreaIntervento");
                _IdAreaIntervento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdAreaIntervento");
                OnIdAreaInterventoChanged();
            }
        }
        private global::System.Guid _IdAreaIntervento;
        partial void OnIdAreaInterventoChanging(global::System.Guid value);
        partial void OnIdAreaInterventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid IdTipoIntervento
        {
            get
            {
                return _IdTipoIntervento;
            }
            set
            {
                OnIdTipoInterventoChanging(value);
                ReportPropertyChanging("IdTipoIntervento");
                _IdTipoIntervento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoIntervento");
                OnIdTipoInterventoChanged();
            }
        }
        private global::System.Guid _IdTipoIntervento;
        partial void OnIdTipoInterventoChanging(global::System.Guid value);
        partial void OnIdTipoInterventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodiceOrdine
        {
            get
            {
                return _CodiceOrdine;
            }
            set
            {
                OnCodiceOrdineChanging(value);
                ReportPropertyChanging("CodiceOrdine");
                _CodiceOrdine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodiceOrdine");
                OnCodiceOrdineChanged();
            }
        }
        private global::System.String _CodiceOrdine;
        partial void OnCodiceOrdineChanging(global::System.String value);
        partial void OnCodiceOrdineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAvvisoIspezione
        {
            get
            {
                return _IsAvvisoIspezione;
            }
            set
            {
                OnIsAvvisoIspezioneChanging(value);
                ReportPropertyChanging("IsAvvisoIspezione");
                _IsAvvisoIspezione = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAvvisoIspezione");
                OnIsAvvisoIspezioneChanged();
            }
        }
        private global::System.Boolean _IsAvvisoIspezione;
        partial void OnIsAvvisoIspezioneChanging(global::System.Boolean value);
        partial void OnIsAvvisoIspezioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSpunta
        {
            get
            {
                return _IsSpunta;
            }
            set
            {
                OnIsSpuntaChanging(value);
                ReportPropertyChanging("IsSpunta");
                _IsSpunta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSpunta");
                OnIsSpuntaChanged();
            }
        }
        private global::System.Boolean _IsSpunta;
        partial void OnIsSpuntaChanging(global::System.Boolean value);
        partial void OnIsSpuntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsReso
        {
            get
            {
                return _IsReso;
            }
            set
            {
                OnIsResoChanging(value);
                ReportPropertyChanging("IsReso");
                _IsReso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsReso");
                OnIsResoChanged();
            }
        }
        private global::System.Boolean _IsReso;
        partial void OnIsResoChanging(global::System.Boolean value);
        partial void OnIsResoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonResoAppaltatore
        {
            get
            {
                return _IsNonResoAppaltatore;
            }
            set
            {
                OnIsNonResoAppaltatoreChanging(value);
                ReportPropertyChanging("IsNonResoAppaltatore");
                _IsNonResoAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonResoAppaltatore");
                OnIsNonResoAppaltatoreChanged();
            }
        }
        private global::System.Boolean _IsNonResoAppaltatore;
        partial void OnIsNonResoAppaltatoreChanging(global::System.Boolean value);
        partial void OnIsNonResoAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonReso20mn
        {
            get
            {
                return _IsNonReso20mn;
            }
            set
            {
                OnIsNonReso20mnChanging(value);
                ReportPropertyChanging("IsNonReso20mn");
                _IsNonReso20mn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonReso20mn");
                OnIsNonReso20mnChanged();
            }
        }
        private global::System.Boolean _IsNonReso20mn;
        partial void OnIsNonReso20mnChanging(global::System.Boolean value);
        partial void OnIsNonReso20mnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNonResoTrenitalia
        {
            get
            {
                return _IsNonResoTrenitalia;
            }
            set
            {
                OnIsNonResoTrenitaliaChanging(value);
                ReportPropertyChanging("IsNonResoTrenitalia");
                _IsNonResoTrenitalia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNonResoTrenitalia");
                OnIsNonResoTrenitaliaChanged();
            }
        }
        private global::System.Boolean _IsNonResoTrenitalia;
        partial void OnIsNonResoTrenitaliaChanging(global::System.Boolean value);
        partial void OnIsNonResoTrenitaliaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRilevatoNonReso
        {
            get
            {
                return _IsRilevatoNonReso;
            }
            set
            {
                OnIsRilevatoNonResoChanging(value);
                ReportPropertyChanging("IsRilevatoNonReso");
                _IsRilevatoNonReso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRilevatoNonReso");
                OnIsRilevatoNonResoChanged();
            }
        }
        private global::System.Boolean _IsRilevatoNonReso;
        partial void OnIsRilevatoNonResoChanging(global::System.Boolean value);
        partial void OnIsRilevatoNonResoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRettifica
        {
            get
            {
                return _IsRettifica;
            }
            set
            {
                OnIsRettificaChanging(value);
                ReportPropertyChanging("IsRettifica");
                _IsRettifica = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRettifica");
                OnIsRettificaChanged();
            }
        }
        private global::System.Boolean _IsRettifica;
        partial void OnIsRettificaChanging(global::System.Boolean value);
        partial void OnIsRettificaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSostituito
        {
            get
            {
                return _IsSostituito;
            }
            set
            {
                OnIsSostituitoChanging(value);
                ReportPropertyChanging("IsSostituito");
                _IsSostituito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSostituito");
                OnIsSostituitoChanged();
            }
        }
        private global::System.Boolean _IsSostituito;
        partial void OnIsSostituitoChanging(global::System.Boolean value);
        partial void OnIsSostituitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasSchedaV
        {
            get
            {
                return _HasSchedaV;
            }
            set
            {
                OnHasSchedaVChanging(value);
                ReportPropertyChanging("HasSchedaV");
                _HasSchedaV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasSchedaV");
                OnHasSchedaVChanged();
            }
        }
        private global::System.Boolean _HasSchedaV;
        partial void OnHasSchedaVChanging(global::System.Boolean value);
        partial void OnHasSchedaVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasSchedaQ
        {
            get
            {
                return _HasSchedaQ;
            }
            set
            {
                OnHasSchedaQChanging(value);
                ReportPropertyChanging("HasSchedaQ");
                _HasSchedaQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasSchedaQ");
                OnHasSchedaQChanged();
            }
        }
        private global::System.Boolean _HasSchedaQ;
        partial void OnHasSchedaQChanging(global::System.Boolean value);
        partial void OnHasSchedaQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AreaInterventoDescrizione
        {
            get
            {
                return _AreaInterventoDescrizione;
            }
            set
            {
                OnAreaInterventoDescrizioneChanging(value);
                ReportPropertyChanging("AreaInterventoDescrizione");
                _AreaInterventoDescrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AreaInterventoDescrizione");
                OnAreaInterventoDescrizioneChanged();
            }
        }
        private global::System.String _AreaInterventoDescrizione;
        partial void OnAreaInterventoDescrizioneChanging(global::System.String value);
        partial void OnAreaInterventoDescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoriaTreno
        {
            get
            {
                return _CategoriaTreno;
            }
            set
            {
                OnCategoriaTrenoChanging(value);
                ReportPropertyChanging("CategoriaTreno");
                _CategoriaTreno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoriaTreno");
                OnCategoriaTrenoChanged();
            }
        }
        private global::System.String _CategoriaTreno;
        partial void OnCategoriaTrenoChanging(global::System.String value);
        partial void OnCategoriaTrenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroTrenoPartenza
        {
            get
            {
                return _NumeroTrenoPartenza;
            }
            set
            {
                OnNumeroTrenoPartenzaChanging(value);
                ReportPropertyChanging("NumeroTrenoPartenza");
                _NumeroTrenoPartenza = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroTrenoPartenza");
                OnNumeroTrenoPartenzaChanged();
            }
        }
        private global::System.String _NumeroTrenoPartenza;
        partial void OnNumeroTrenoPartenzaChanging(global::System.String value);
        partial void OnNumeroTrenoPartenzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataTrenoPartenza
        {
            get
            {
                return _DataTrenoPartenza;
            }
            set
            {
                OnDataTrenoPartenzaChanging(value);
                ReportPropertyChanging("DataTrenoPartenza");
                _DataTrenoPartenza = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataTrenoPartenza");
                OnDataTrenoPartenzaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataTrenoPartenza;
        partial void OnDataTrenoPartenzaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataTrenoPartenzaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoInterventoDescrizione
        {
            get
            {
                return _TipoInterventoDescrizione;
            }
            set
            {
                OnTipoInterventoDescrizioneChanging(value);
                ReportPropertyChanging("TipoInterventoDescrizione");
                _TipoInterventoDescrizione = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoInterventoDescrizione");
                OnTipoInterventoDescrizioneChanged();
            }
        }
        private global::System.String _TipoInterventoDescrizione;
        partial void OnTipoInterventoDescrizioneChanging(global::System.String value);
        partial void OnTipoInterventoDescrizioneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInizioProgrammata
        {
            get
            {
                return _DataInizioProgrammata;
            }
            set
            {
                OnDataInizioProgrammataChanging(value);
                ReportPropertyChanging("DataInizioProgrammata");
                _DataInizioProgrammata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInizioProgrammata");
                OnDataInizioProgrammataChanged();
            }
        }
        private global::System.DateTime _DataInizioProgrammata;
        partial void OnDataInizioProgrammataChanging(global::System.DateTime value);
        partial void OnDataInizioProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataFineProgrammata
        {
            get
            {
                return _DataFineProgrammata;
            }
            set
            {
                OnDataFineProgrammataChanging(value);
                ReportPropertyChanging("DataFineProgrammata");
                _DataFineProgrammata = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFineProgrammata");
                OnDataFineProgrammataChanged();
            }
        }
        private global::System.DateTime _DataFineProgrammata;
        partial void OnDataFineProgrammataChanging(global::System.DateTime value);
        partial void OnDataFineProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComposizioneProgrammata
        {
            get
            {
                return _ComposizioneProgrammata;
            }
            set
            {
                OnComposizioneProgrammataChanging(value);
                ReportPropertyChanging("ComposizioneProgrammata");
                _ComposizioneProgrammata = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ComposizioneProgrammata");
                OnComposizioneProgrammataChanged();
            }
        }
        private global::System.String _ComposizioneProgrammata;
        partial void OnComposizioneProgrammataChanging(global::System.String value);
        partial void OnComposizioneProgrammataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInizioConsuntivataAppaltatore
        {
            get
            {
                return _DataInizioConsuntivataAppaltatore;
            }
            set
            {
                OnDataInizioConsuntivataAppaltatoreChanging(value);
                ReportPropertyChanging("DataInizioConsuntivataAppaltatore");
                _DataInizioConsuntivataAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInizioConsuntivataAppaltatore");
                OnDataInizioConsuntivataAppaltatoreChanged();
            }
        }
        private global::System.DateTime _DataInizioConsuntivataAppaltatore;
        partial void OnDataInizioConsuntivataAppaltatoreChanging(global::System.DateTime value);
        partial void OnDataInizioConsuntivataAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataFineConsuntivataAppaltatore
        {
            get
            {
                return _DataFineConsuntivataAppaltatore;
            }
            set
            {
                OnDataFineConsuntivataAppaltatoreChanging(value);
                ReportPropertyChanging("DataFineConsuntivataAppaltatore");
                _DataFineConsuntivataAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFineConsuntivataAppaltatore");
                OnDataFineConsuntivataAppaltatoreChanged();
            }
        }
        private global::System.DateTime _DataFineConsuntivataAppaltatore;
        partial void OnDataFineConsuntivataAppaltatoreChanging(global::System.DateTime value);
        partial void OnDataFineConsuntivataAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsProgrammato
        {
            get
            {
                return _IsProgrammato;
            }
            set
            {
                OnIsProgrammatoChanging(value);
                ReportPropertyChanging("IsProgrammato");
                _IsProgrammato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProgrammato");
                OnIsProgrammatoChanged();
            }
        }
        private global::System.Boolean _IsProgrammato;
        partial void OnIsProgrammatoChanging(global::System.Boolean value);
        partial void OnIsProgrammatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPLX
        {
            get
            {
                return _IsPLX;
            }
            set
            {
                OnIsPLXChanging(value);
                ReportPropertyChanging("IsPLX");
                _IsPLX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPLX");
                OnIsPLXChanged();
            }
        }
        private global::System.Boolean _IsPLX;
        partial void OnIsPLXChanging(global::System.Boolean value);
        partial void OnIsPLXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEstemporaneo
        {
            get
            {
                return _IsEstemporaneo;
            }
            set
            {
                OnIsEstemporaneoChanging(value);
                ReportPropertyChanging("IsEstemporaneo");
                _IsEstemporaneo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEstemporaneo");
                OnIsEstemporaneoChanged();
            }
        }
        private global::System.Boolean _IsEstemporaneo;
        partial void OnIsEstemporaneoChanging(global::System.Boolean value);
        partial void OnIsEstemporaneoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSostitutivo
        {
            get
            {
                return _IsSostitutivo;
            }
            set
            {
                OnIsSostitutivoChanging(value);
                ReportPropertyChanging("IsSostitutivo");
                _IsSostitutivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSostitutivo");
                OnIsSostitutivoChanged();
            }
        }
        private global::System.Boolean _IsSostitutivo;
        partial void OnIsSostitutivoChanging(global::System.Boolean value);
        partial void OnIsSostitutivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasTreni
        {
            get
            {
                return _HasTreni;
            }
            set
            {
                OnHasTreniChanging(value);
                ReportPropertyChanging("HasTreni");
                _HasTreni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasTreni");
                OnHasTreniChanged();
            }
        }
        private global::System.Boolean _HasTreni;
        partial void OnHasTreniChanging(global::System.Boolean value);
        partial void OnHasTreniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasRotabiliSingoli
        {
            get
            {
                return _HasRotabiliSingoli;
            }
            set
            {
                OnHasRotabiliSingoliChanging(value);
                ReportPropertyChanging("HasRotabiliSingoli");
                _HasRotabiliSingoli = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasRotabiliSingoli");
                OnHasRotabiliSingoliChanged();
            }
        }
        private global::System.Boolean _HasRotabiliSingoli;
        partial void OnHasRotabiliSingoliChanging(global::System.Boolean value);
        partial void OnHasRotabiliSingoliChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasCarozze
        {
            get
            {
                return _HasCarozze;
            }
            set
            {
                OnHasCarozzeChanging(value);
                ReportPropertyChanging("HasCarozze");
                _HasCarozze = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasCarozze");
                OnHasCarozzeChanged();
            }
        }
        private global::System.Boolean _HasCarozze;
        partial void OnHasCarozzeChanging(global::System.Boolean value);
        partial void OnHasCarozzeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasLocomotive
        {
            get
            {
                return _HasLocomotive;
            }
            set
            {
                OnHasLocomotiveChanging(value);
                ReportPropertyChanging("HasLocomotive");
                _HasLocomotive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasLocomotive");
                OnHasLocomotiveChanged();
            }
        }
        private global::System.Boolean _HasLocomotive;
        partial void OnHasLocomotiveChanging(global::System.Boolean value);
        partial void OnHasLocomotiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoTrenitaliaRispettoAlProgramma
        {
            get
            {
                return _IsModificatoTrenitaliaRispettoAlProgramma;
            }
            set
            {
                OnIsModificatoTrenitaliaRispettoAlProgrammaChanging(value);
                ReportPropertyChanging("IsModificatoTrenitaliaRispettoAlProgramma");
                _IsModificatoTrenitaliaRispettoAlProgramma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoTrenitaliaRispettoAlProgramma");
                OnIsModificatoTrenitaliaRispettoAlProgrammaChanged();
            }
        }
        private global::System.Boolean _IsModificatoTrenitaliaRispettoAlProgramma;
        partial void OnIsModificatoTrenitaliaRispettoAlProgrammaChanging(global::System.Boolean value);
        partial void OnIsModificatoTrenitaliaRispettoAlProgrammaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoAppaltatoreRispettoAlProgramma
        {
            get
            {
                return _IsModificatoAppaltatoreRispettoAlProgramma;
            }
            set
            {
                OnIsModificatoAppaltatoreRispettoAlProgrammaChanging(value);
                ReportPropertyChanging("IsModificatoAppaltatoreRispettoAlProgramma");
                _IsModificatoAppaltatoreRispettoAlProgramma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoAppaltatoreRispettoAlProgramma");
                OnIsModificatoAppaltatoreRispettoAlProgrammaChanged();
            }
        }
        private global::System.Boolean _IsModificatoAppaltatoreRispettoAlProgramma;
        partial void OnIsModificatoAppaltatoreRispettoAlProgrammaChanging(global::System.Boolean value);
        partial void OnIsModificatoAppaltatoreRispettoAlProgrammaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsModificatoTrenitaliaRispettoAllAppaltatore
        {
            get
            {
                return _IsModificatoTrenitaliaRispettoAllAppaltatore;
            }
            set
            {
                OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanging(value);
                ReportPropertyChanging("IsModificatoTrenitaliaRispettoAllAppaltatore");
                _IsModificatoTrenitaliaRispettoAllAppaltatore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsModificatoTrenitaliaRispettoAllAppaltatore");
                OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanged();
            }
        }
        private global::System.Boolean _IsModificatoTrenitaliaRispettoAllAppaltatore;
        partial void OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanging(global::System.Boolean value);
        partial void OnIsModificatoTrenitaliaRispettoAllAppaltatoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();

        #endregion
    
    }

    #endregion
    
}
