using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Denormalizers.DTO.PEC
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioAnagrafiche : MessaggioBase
    {

        private Lotto[] lottiField;

        private GruppoOggettoIntervento[] gruppiOggettoInterventoField;

        private TipoIntervento[] tipiInterventoField;

        private Committente[] committentiField;

        private CausaleNonResa[] causaliNonReseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Lotto[] Lotti
        {
            get
            {
                return this.lottiField;
            }
            set
            {
                this.lottiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public GruppoOggettoIntervento[] GruppiOggettoIntervento
        {
            get
            {
                return this.gruppiOggettoInterventoField;
            }
            set
            {
                this.gruppiOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public TipoIntervento[] TipiIntervento
        {
            get
            {
                return this.tipiInterventoField;
            }
            set
            {
                this.tipiInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Committente[] Committenti
        {
            get
            {
                return this.committentiField;
            }
            set
            {
                this.committentiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public CausaleNonResa[] CausaliNonRese
        {
            get
            {
                return this.causaliNonReseField;
            }
            set
            {
                this.causaliNonReseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class Lotto
    {

        private int idLottoField;

        private string mnemoLottoField;

        private string descrizioneField;

        private System.DateTime dataInizioField;

        private System.DateTime dataFineField;

        private bool dataFineFieldSpecified;

        private AreaIntervento[] areeInterventoField;

        /// <remarks/>
        public int IdLotto
        {
            get
            {
                return this.idLottoField;
            }
            set
            {
                this.idLottoField = value;
            }
        }

        /// <remarks/>
        public string MnemoLotto
        {
            get
            {
                return this.mnemoLottoField;
            }
            set
            {
                this.mnemoLottoField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataFine
        {
            get
            {
                return this.dataFineField;
            }
            set
            {
                this.dataFineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFineSpecified
        {
            get
            {
                return this.dataFineFieldSpecified;
            }
            set
            {
                this.dataFineFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public AreaIntervento[] AreeIntervento
        {
            get
            {
                return this.areeInterventoField;
            }
            set
            {
                this.areeInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class AreaIntervento
    {

        private short idAreaInterventoField;

        private string descrizioneField;

        private TipoAreaInterventiEnum tipoAreaInterventoField;

        private System.DateTime dataInizioField;

        private System.DateTime dataFineField;

        private bool dataFineFieldSpecified;

        private short[] idTipiInterventoField;

        /// <remarks/>
        public short IdAreaIntervento
        {
            get
            {
                return this.idAreaInterventoField;
            }
            set
            {
                this.idAreaInterventoField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public TipoAreaInterventiEnum TipoAreaIntervento
        {
            get
            {
                return this.tipoAreaInterventoField;
            }
            set
            {
                this.tipoAreaInterventoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataFine
        {
            get
            {
                return this.dataFineField;
            }
            set
            {
                this.dataFineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFineSpecified
        {
            get
            {
                return this.dataFineFieldSpecified;
            }
            set
            {
                this.dataFineFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public short[] IdTipiIntervento
        {
            get
            {
                return this.idTipiInterventoField;
            }
            set
            {
                this.idTipiInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum TipoAreaInterventiEnum
    {

        /// <remarks/>
        Impianto,

        /// <remarks/>
        Cantiere,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class OggettoIntervento
    {

        private int idField;

        private string descrizioneField;

        private int quantitaField;

        private int idTipoOggettoInterventoField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public int Quantita
        {
            get
            {
                return this.quantitaField;
            }
            set
            {
                this.quantitaField = value;
            }
        }

        /// <remarks/>
        public int IdTipoOggettoIntervento
        {
            get
            {
                return this.idTipoOggettoInterventoField;
            }
            set
            {
                this.idTipoOggettoInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class Intervento
    {

        private int idFotoInterventoField;

        private short idAreaInterventoField;

        private int idInterventoSuperField;

        private bool idInterventoSuperFieldSpecified;

        private string idInterventoAppaltatoreField;

        private short idTipoInterventoField;

        private int idCommittenteField;

        private string numeroTrenoPartenzaField;

        private System.DateTime dataOraTrenoPartenzaField;

        private bool dataOraTrenoPartenzaFieldSpecified;

        private string numeroTrenoArrivoField;

        private System.DateTime dataOraTrenoArrivoField;

        private bool dataOraTrenoArrivoFieldSpecified;

        private string turnoTrenoField;

        private string rigaTurnoTrenoField;

        private string noteField;

        private System.DateTime inizioField;

        private System.DateTime fineField;

        private int numeroPostiSedereField;

        private bool numeroPostiSedereFieldSpecified;

        private OggettoIntervento[] oggettiField;

        private StatoInterventoEnum statoField;

        /// <remarks/>
        public int IdFotoIntervento
        {
            get
            {
                return this.idFotoInterventoField;
            }
            set
            {
                this.idFotoInterventoField = value;
            }
        }

        /// <remarks/>
        public short IdAreaIntervento
        {
            get
            {
                return this.idAreaInterventoField;
            }
            set
            {
                this.idAreaInterventoField = value;
            }
        }

        /// <remarks/>
        public int IdInterventoSuper
        {
            get
            {
                return this.idInterventoSuperField;
            }
            set
            {
                this.idInterventoSuperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdInterventoSuperSpecified
        {
            get
            {
                return this.idInterventoSuperFieldSpecified;
            }
            set
            {
                this.idInterventoSuperFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string IdInterventoAppaltatore
        {
            get
            {
                return this.idInterventoAppaltatoreField;
            }
            set
            {
                this.idInterventoAppaltatoreField = value;
            }
        }

        /// <remarks/>
        public short IdTipoIntervento
        {
            get
            {
                return this.idTipoInterventoField;
            }
            set
            {
                this.idTipoInterventoField = value;
            }
        }

        /// <remarks/>
        public int IdCommittente
        {
            get
            {
                return this.idCommittenteField;
            }
            set
            {
                this.idCommittenteField = value;
            }
        }

        /// <remarks/>
        public string NumeroTrenoPartenza
        {
            get
            {
                return this.numeroTrenoPartenzaField;
            }
            set
            {
                this.numeroTrenoPartenzaField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataOraTrenoPartenza
        {
            get
            {
                return this.dataOraTrenoPartenzaField;
            }
            set
            {
                this.dataOraTrenoPartenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataOraTrenoPartenzaSpecified
        {
            get
            {
                return this.dataOraTrenoPartenzaFieldSpecified;
            }
            set
            {
                this.dataOraTrenoPartenzaFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NumeroTrenoArrivo
        {
            get
            {
                return this.numeroTrenoArrivoField;
            }
            set
            {
                this.numeroTrenoArrivoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataOraTrenoArrivo
        {
            get
            {
                return this.dataOraTrenoArrivoField;
            }
            set
            {
                this.dataOraTrenoArrivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataOraTrenoArrivoSpecified
        {
            get
            {
                return this.dataOraTrenoArrivoFieldSpecified;
            }
            set
            {
                this.dataOraTrenoArrivoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TurnoTreno
        {
            get
            {
                return this.turnoTrenoField;
            }
            set
            {
                this.turnoTrenoField = value;
            }
        }

        /// <remarks/>
        public string RigaTurnoTreno
        {
            get
            {
                return this.rigaTurnoTrenoField;
            }
            set
            {
                this.rigaTurnoTrenoField = value;
            }
        }

        /// <remarks/>
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Inizio
        {
            get
            {
                return this.inizioField;
            }
            set
            {
                this.inizioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Fine
        {
            get
            {
                return this.fineField;
            }
            set
            {
                this.fineField = value;
            }
        }

        /// <remarks/>
        public int NumeroPostiSedere
        {
            get
            {
                return this.numeroPostiSedereField;
            }
            set
            {
                this.numeroPostiSedereField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroPostiSedereSpecified
        {
            get
            {
                return this.numeroPostiSedereFieldSpecified;
            }
            set
            {
                this.numeroPostiSedereFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Oggetto", IsNullable = false)]
        public OggettoIntervento[] Oggetti
        {
            get
            {
                return this.oggettiField;
            }
            set
            {
                this.oggettiField = value;
            }
        }

        /// <remarks/>
        public StatoInterventoEnum Stato
        {
            get
            {
                return this.statoField;
            }
            set
            {
                this.statoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum StatoInterventoEnum
    {

        /// <remarks/>
        PLX,

        /// <remarks/>
        PLG,

        /// <remarks/>
        Estemporaneo,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class CorpoSchedaVQ
    {

        private string particolareField;

        private System.Nullable<decimal> pesoField;

        private string requisitoField;

        private System.Nullable<bool> resultField;

        /// <remarks/>
        public string Particolare
        {
            get
            {
                return this.particolareField;
            }
            set
            {
                this.particolareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Peso
        {
            get
            {
                return this.pesoField;
            }
            set
            {
                this.pesoField = value;
            }
        }

        /// <remarks/>
        public string Requisito
        {
            get
            {
                return this.requisitoField;
            }
            set
            {
                this.requisitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class ZonaSchedaVQ
    {

        private int zonaIdField;

        private string descrizioneField;

        private CorpoSchedaVQ[] corpiField;

        /// <remarks/>
        public int ZonaId
        {
            get
            {
                return this.zonaIdField;
            }
            set
            {
                this.zonaIdField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Corpo", IsNullable = false)]
        public CorpoSchedaVQ[] Corpi
        {
            get
            {
                return this.corpiField;
            }
            set
            {
                this.corpiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class HeaderSchedaVQ
    {

        private string agenteField;

        private string cantiereField;

        private string categoriaTrenoField;

        private string codiceCarozzaField;

        private string codiceLocomotivaField;

        private string composizioneCarozzeField;

        private System.DateTime dataField;

        private string impiantoField;

        private string impresaField;

        private int idInterventoSuperField;

        private string idInterventoAppaltatoreField;

        private System.Nullable<int> numeroItemSchedaNegativaConCabinaGuidaField;

        private System.Nullable<int> numeroItemSchedaNegativaSenzaCabinaGuidaField;

        private System.Nullable<short> numeroTotaleCarozzeField;

        private string numeroTrenoField;

        private System.DateTime oraFineField;

        private System.DateTime oraInizioField;

        private int schedaVQNumeroField;

        private string tipoInterventoDescrizioneField;

        private string tipoInterventoSiglaField;

        private string tipoRotField;

        private string tipoSchedaField;

        private string titleSchedaField;

        private string utenteField;

        private System.Nullable<bool> verificaPositivaField;

        private System.Nullable<bool> cabinaDiGuidaCheckedField;

        private System.Nullable<decimal> percentualeNonConformitaField;

        private System.Nullable<bool> cancellataField;

        /// <remarks/>
        public string Agente
        {
            get
            {
                return this.agenteField;
            }
            set
            {
                this.agenteField = value;
            }
        }

        /// <remarks/>
        public string Cantiere
        {
            get
            {
                return this.cantiereField;
            }
            set
            {
                this.cantiereField = value;
            }
        }

        /// <remarks/>
        public string CategoriaTreno
        {
            get
            {
                return this.categoriaTrenoField;
            }
            set
            {
                this.categoriaTrenoField = value;
            }
        }

        /// <remarks/>
        public string CodiceCarozza
        {
            get
            {
                return this.codiceCarozzaField;
            }
            set
            {
                this.codiceCarozzaField = value;
            }
        }

        /// <remarks/>
        public string CodiceLocomotiva
        {
            get
            {
                return this.codiceLocomotivaField;
            }
            set
            {
                this.codiceLocomotivaField = value;
            }
        }

        /// <remarks/>
        public string ComposizioneCarozze
        {
            get
            {
                return this.composizioneCarozzeField;
            }
            set
            {
                this.composizioneCarozzeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public string Impianto
        {
            get
            {
                return this.impiantoField;
            }
            set
            {
                this.impiantoField = value;
            }
        }

        /// <remarks/>
        public string Impresa
        {
            get
            {
                return this.impresaField;
            }
            set
            {
                this.impresaField = value;
            }
        }

        /// <remarks/>
        public int IdInterventoSuper
        {
            get
            {
                return this.idInterventoSuperField;
            }
            set
            {
                this.idInterventoSuperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdInterventoAppaltatore
        {
            get
            {
                return this.idInterventoAppaltatoreField;
            }
            set
            {
                this.idInterventoAppaltatoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> NumeroItemSchedaNegativaConCabinaGuida
        {
            get
            {
                return this.numeroItemSchedaNegativaConCabinaGuidaField;
            }
            set
            {
                this.numeroItemSchedaNegativaConCabinaGuidaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> NumeroItemSchedaNegativaSenzaCabinaGuida
        {
            get
            {
                return this.numeroItemSchedaNegativaSenzaCabinaGuidaField;
            }
            set
            {
                this.numeroItemSchedaNegativaSenzaCabinaGuidaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<short> NumeroTotaleCarozze
        {
            get
            {
                return this.numeroTotaleCarozzeField;
            }
            set
            {
                this.numeroTotaleCarozzeField = value;
            }
        }

        /// <remarks/>
        public string NumeroTreno
        {
            get
            {
                return this.numeroTrenoField;
            }
            set
            {
                this.numeroTrenoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime OraFine
        {
            get
            {
                return this.oraFineField;
            }
            set
            {
                this.oraFineField = value;
            }
        }

        /// <remarks/>
        public System.DateTime OraInizio
        {
            get
            {
                return this.oraInizioField;
            }
            set
            {
                this.oraInizioField = value;
            }
        }

        /// <remarks/>
        public int SchedaVQNumero
        {
            get
            {
                return this.schedaVQNumeroField;
            }
            set
            {
                this.schedaVQNumeroField = value;
            }
        }

        /// <remarks/>
        public string TipoInterventoDescrizione
        {
            get
            {
                return this.tipoInterventoDescrizioneField;
            }
            set
            {
                this.tipoInterventoDescrizioneField = value;
            }
        }

        /// <remarks/>
        public string TipoInterventoSigla
        {
            get
            {
                return this.tipoInterventoSiglaField;
            }
            set
            {
                this.tipoInterventoSiglaField = value;
            }
        }

        /// <remarks/>
        public string TipoRot
        {
            get
            {
                return this.tipoRotField;
            }
            set
            {
                this.tipoRotField = value;
            }
        }

        /// <remarks/>
        public string TipoScheda
        {
            get
            {
                return this.tipoSchedaField;
            }
            set
            {
                this.tipoSchedaField = value;
            }
        }

        /// <remarks/>
        public string TitleScheda
        {
            get
            {
                return this.titleSchedaField;
            }
            set
            {
                this.titleSchedaField = value;
            }
        }

        /// <remarks/>
        public string Utente
        {
            get
            {
                return this.utenteField;
            }
            set
            {
                this.utenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> VerificaPositiva
        {
            get
            {
                return this.verificaPositivaField;
            }
            set
            {
                this.verificaPositivaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> CabinaDiGuidaChecked
        {
            get
            {
                return this.cabinaDiGuidaCheckedField;
            }
            set
            {
                this.cabinaDiGuidaCheckedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> PercentualeNonConformita
        {
            get
            {
                return this.percentualeNonConformitaField;
            }
            set
            {
                this.percentualeNonConformitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Cancellata
        {
            get
            {
                return this.cancellataField;
            }
            set
            {
                this.cancellataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class CausaleNonResa
    {

        private int idField;

        private string descrizioneField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class Committente
    {

        private short idComittenteField;

        private string mnemoCommittenteField;

        private string descrizioneField;

        /// <remarks/>
        public short IdComittente
        {
            get
            {
                return this.idComittenteField;
            }
            set
            {
                this.idComittenteField = value;
            }
        }

        /// <remarks/>
        public string MnemoCommittente
        {
            get
            {
                return this.mnemoCommittenteField;
            }
            set
            {
                this.mnemoCommittenteField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class TipoIntervento
    {

        private short idTipoInterventoField;

        private string mnemoTipoInterventoField;

        private string descrizioneField;

        private SettoreInterventoEnum settoreInterventoField;

        private short[] idGruppiOggettoInterventoField;

        private short[] idAreeInterventoField;

        /// <remarks/>
        public short IdTipoIntervento
        {
            get
            {
                return this.idTipoInterventoField;
            }
            set
            {
                this.idTipoInterventoField = value;
            }
        }

        /// <remarks/>
        public string MnemoTipoIntervento
        {
            get
            {
                return this.mnemoTipoInterventoField;
            }
            set
            {
                this.mnemoTipoInterventoField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public SettoreInterventoEnum SettoreIntervento
        {
            get
            {
                return this.settoreInterventoField;
            }
            set
            {
                this.settoreInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public short[] IdGruppiOggettoIntervento
        {
            get
            {
                return this.idGruppiOggettoInterventoField;
            }
            set
            {
                this.idGruppiOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public short[] IdAreeIntervento
        {
            get
            {
                return this.idAreeInterventoField;
            }
            set
            {
                this.idAreeInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum SettoreInterventoEnum
    {
        //used to initialize the enum with a "nullable" value, so that not finding the field will not produce Rotabili.
        None,

        /// <remarks/>
        Rotabili,

        /// <remarks/>
        RotabiliInManutenzione,

        /// <remarks/>
        Ambiente,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class TipoOggettoIntervento
    {

        private short idTipoOggettoInterventoField;

        private string mnemoTipoOggettoInterventoField;

        private string descrizioneField;

        /// <remarks/>
        public short IdTipoOggettoIntervento
        {
            get
            {
                return this.idTipoOggettoInterventoField;
            }
            set
            {
                this.idTipoOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        public string MnemoTipoOggettoIntervento
        {
            get
            {
                return this.mnemoTipoOggettoInterventoField;
            }
            set
            {
                this.mnemoTipoOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class GruppoOggettoIntervento
    {

        private short idGruppoOggettoInterventoField;

        private string mnemoGruppoOggettoInterventoField;

        private string descrizioneField;

        private TipoOggettoIntervento[] tipiOggettoInterventoField;

        private short[] idTipiInterventoField;

        /// <remarks/>
        public short IdGruppoOggettoIntervento
        {
            get
            {
                return this.idGruppoOggettoInterventoField;
            }
            set
            {
                this.idGruppoOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        public string MnemoGruppoOggettoIntervento
        {
            get
            {
                return this.mnemoGruppoOggettoInterventoField;
            }
            set
            {
                this.mnemoGruppoOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public TipoOggettoIntervento[] TipiOggettoIntervento
        {
            get
            {
                return this.tipiOggettoInterventoField;
            }
            set
            {
                this.tipiOggettoInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public short[] IdTipiIntervento
        {
            get
            {
                return this.idTipiInterventoField;
            }
            set
            {
                this.idTipiInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public partial class Header
    {

        private string guidField;

        /// <remarks/>
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioConsuntivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioPLX))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioVerifica))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioPiano))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagioSchedaVQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessaggioAnagrafiche))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public abstract partial class MessaggioBase
    {

        private Header headerField;

        /// <remarks/>
        public Header Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessagioSchedaVQ : MessaggioBase
    {

        private HeaderSchedaVQ headerSchedaField;

        private ZonaSchedaVQ[] zoneSchedaField;

        /// <remarks/>
        public HeaderSchedaVQ HeaderScheda
        {
            get
            {
                return this.headerSchedaField;
            }
            set
            {
                this.headerSchedaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Zona", IsNullable = false)]
        public ZonaSchedaVQ[] ZoneScheda
        {
            get
            {
                return this.zoneSchedaField;
            }
            set
            {
                this.zoneSchedaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioPiano : MessaggioBase
    {

        private TipoPianoEnum tipoPianoField;

        private StatoPianoEnum statoPianoField;

        private string mnemoLottoField;

        private System.DateTime dataField;

        private SettoreInterventoEnum settoreInterventoField;

        private Intervento[] interventiField;

        /// <remarks/>
        public TipoPianoEnum TipoPiano
        {
            get
            {
                return this.tipoPianoField;
            }
            set
            {
                this.tipoPianoField = value;
            }
        }

        /// <remarks/>
        public StatoPianoEnum StatoPiano
        {
            get
            {
                return this.statoPianoField;
            }
            set
            {
                this.statoPianoField = value;
            }
        }

        /// <remarks/>
        public string MnemoLotto
        {
            get
            {
                return this.mnemoLottoField;
            }
            set
            {
                this.mnemoLottoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public SettoreInterventoEnum SettoreIntervento
        {
            get
            {
                return this.settoreInterventoField;
            }
            set
            {
                this.settoreInterventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Intervento[] Interventi
        {
            get
            {
                return this.interventiField;
            }
            set
            {
                this.interventiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum TipoPianoEnum
    {

        /// <remarks/>
        PAP,

        /// <remarks/>
        PMP,

        /// <remarks/>
        PLS,

        /// <remarks/>
        PLG,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum StatoPianoEnum
    {

        /// <remarks/>
        Valido,

        /// <remarks/>
        NonDisponibile,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioVerifica : MessaggioBase
    {

        private int idInterventoField;

        /// <remarks/>
        public int IdIntervento
        {
            get
            {
                return this.idInterventoField;
            }
            set
            {
                this.idInterventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioPLX : MessaggioBase
    {

        private Intervento interventoField;

        /// <remarks/>
        public Intervento Intervento
        {
            get
            {
                return this.interventoField;
            }
            set
            {
                this.interventoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioConsuntivo : MessaggioBase
    {

        private SettoreInterventoEnum settoreInterventoField;

        private Intervento interventoField;

        private StatoConsuntivazioneEnum statoConsuntivazioneField;

        private short idCausaleNonResaField;

        private bool idCausaleNonResaFieldSpecified;

        private int idInterventoSostituitoAppaltatoreField;

        private bool idInterventoSostituitoAppaltatoreFieldSpecified;

        private int idInterventoSostituitoSuperField;

        private bool idInterventoSostituitoSuperFieldSpecified;

        private bool indicatoreRilevazioneInsettiField;

        private bool indicatoreRilevazioneInsettiFieldSpecified;

        private int numeroOrdineLavoroField;

        private bool numeroOrdineLavoroFieldSpecified;

        /// <remarks/>
        public SettoreInterventoEnum SettoreIntervento
        {
            get
            {
                return this.settoreInterventoField;
            }
            set
            {
                this.settoreInterventoField = value;
            }
        }

        /// <remarks/>
        public Intervento Intervento
        {
            get
            {
                return this.interventoField;
            }
            set
            {
                this.interventoField = value;
            }
        }

        /// <remarks/>
        public StatoConsuntivazioneEnum StatoConsuntivazione
        {
            get
            {
                return this.statoConsuntivazioneField;
            }
            set
            {
                this.statoConsuntivazioneField = value;
            }
        }

        /// <remarks/>
        public short IdCausaleNonResa
        {
            get
            {
                return this.idCausaleNonResaField;
            }
            set
            {
                this.idCausaleNonResaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdCausaleNonResaSpecified
        {
            get
            {
                return this.idCausaleNonResaFieldSpecified;
            }
            set
            {
                this.idCausaleNonResaFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int IdInterventoSostituitoAppaltatore
        {
            get
            {
                return this.idInterventoSostituitoAppaltatoreField;
            }
            set
            {
                this.idInterventoSostituitoAppaltatoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdInterventoSostituitoAppaltatoreSpecified
        {
            get
            {
                return this.idInterventoSostituitoAppaltatoreFieldSpecified;
            }
            set
            {
                this.idInterventoSostituitoAppaltatoreFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int IdInterventoSostituitoSuper
        {
            get
            {
                return this.idInterventoSostituitoSuperField;
            }
            set
            {
                this.idInterventoSostituitoSuperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdInterventoSostituitoSuperSpecified
        {
            get
            {
                return this.idInterventoSostituitoSuperFieldSpecified;
            }
            set
            {
                this.idInterventoSostituitoSuperFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IndicatoreRilevazioneInsetti
        {
            get
            {
                return this.indicatoreRilevazioneInsettiField;
            }
            set
            {
                this.indicatoreRilevazioneInsettiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndicatoreRilevazioneInsettiSpecified
        {
            get
            {
                return this.indicatoreRilevazioneInsettiFieldSpecified;
            }
            set
            {
                this.indicatoreRilevazioneInsettiFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int NumeroOrdineLavoro
        {
            get
            {
                return this.numeroOrdineLavoroField;
            }
            set
            {
                this.numeroOrdineLavoroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroOrdineLavoroSpecified
        {
            get
            {
                return this.numeroOrdineLavoroFieldSpecified;
            }
            set
            {
                this.numeroOrdineLavoroFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    public enum StatoConsuntivazioneEnum
    {

        /// <remarks/>
        Reso,

        /// <remarks/>
        NonResoAppaltatore,

        /// <remarks/>
        NonResoTrenitalia,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:TSF.SuperIA.ServiceModel.v1", IsNullable = false)]
    public partial class MessaggioFault : MessaggioBase
    {

        private string guidMessaggioErratoField;

        private string[] motiviField;

        /// <remarks/>
        public string GuidMessaggioErrato
        {
            get
            {
                return this.guidMessaggioErratoField;
            }
            set
            {
                this.guidMessaggioErratoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public string[] Motivi
        {
            get
            {
                return this.motiviField;
            }
            set
            {
                this.motiviField = value;
            }
        }
    }

}
