USE [master]
GO


CREATE DATABASE [Super2010ReadModel] ON  PRIMARY 
( NAME = N'Super2010ReadModel', FILENAME = N'D:\Databases\Super2010ReadModel.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Super2010ReadModel_log', FILENAME = N'D:\Databases\Super2010ReadModel_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyNotesReadModel] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Super2010ReadModel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Super2010ReadModel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET ARITHABORT OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Super2010ReadModel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Super2010ReadModel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Super2010ReadModel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Super2010ReadModel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Super2010ReadModel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Super2010ReadModel] SET  READ_WRITE 
GO

ALTER DATABASE [Super2010ReadModel] SET RECOVERY FULL 
GO

ALTER DATABASE [Super2010ReadModel] SET  MULTI_USER 
GO

ALTER DATABASE [Super2010ReadModel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Super2010ReadModel] SET DB_CHAINING OFF 
GO
	